  Running command git clone --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-u4lhcdg7/transformers_e89ec3ffc51c4aa5b4258d8d47ad58d2
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-u4lhcdg7/peft_d88a89806c8b4bcca43ba60c30f09db7
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-u4lhcdg7/accelerate_c57af791522142978c6457231fdc9281
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]Loading checkpoint shards:  11%|█         | 1/9 [00:06<00:48,  6.06s/it]Loading checkpoint shards:  22%|██▏       | 2/9 [00:11<00:40,  5.83s/it]Loading checkpoint shards:  33%|███▎      | 3/9 [00:16<00:32,  5.47s/it]Loading checkpoint shards:  44%|████▍     | 4/9 [00:21<00:26,  5.35s/it]Loading checkpoint shards:  56%|█████▌    | 5/9 [00:26<00:20,  5.20s/it]Loading checkpoint shards:  67%|██████▋   | 6/9 [00:32<00:15,  5.18s/it]Loading checkpoint shards:  78%|███████▊  | 7/9 [00:37<00:10,  5.18s/it]Loading checkpoint shards:  89%|████████▉ | 8/9 [00:49<00:07,  7.29s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:56<00:00,  7.29s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:56<00:00,  6.25s/it]
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/generation/utils.py:1261: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
