  Running command git clone --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-sfexi0u9/transformers_b7a7c053eaa94203a4db7262c9a63345
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-sfexi0u9/peft_23eda606a60c4dd78b18678f56c4c014
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-sfexi0u9/accelerate_11878be9bc3c4dee9cfc8f2ca015de20
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]Loading checkpoint shards:  11%|█         | 1/9 [00:08<01:07,  8.45s/it]Loading checkpoint shards:  22%|██▏       | 2/9 [00:14<00:50,  7.28s/it]Loading checkpoint shards:  33%|███▎      | 3/9 [00:20<00:39,  6.52s/it]Loading checkpoint shards:  44%|████▍     | 4/9 [00:25<00:29,  5.97s/it]Loading checkpoint shards:  56%|█████▌    | 5/9 [00:30<00:22,  5.72s/it]Loading checkpoint shards:  67%|██████▋   | 6/9 [00:36<00:16,  5.63s/it]Loading checkpoint shards:  78%|███████▊  | 7/9 [00:41<00:10,  5.49s/it]Loading checkpoint shards:  89%|████████▉ | 8/9 [00:46<00:05,  5.45s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:51<00:00,  5.09s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:51<00:00,  5.69s/it]
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/generation/utils.py:1261: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
