  Running command git clone --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-n7k2zo2h/transformers_a1189e00b8514894b14f6e5def0c232b
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-n7k2zo2h/peft_c3617f0a1d8c4c73a2525d18805b719e
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-n7k2zo2h/accelerate_f09018c1e9e84705b98d510453c92a78
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]Loading checkpoint shards:  11%|█         | 1/9 [00:07<01:03,  7.92s/it]Loading checkpoint shards:  22%|██▏       | 2/9 [00:15<00:52,  7.45s/it]Loading checkpoint shards:  33%|███▎      | 3/9 [00:22<00:45,  7.51s/it]Loading checkpoint shards:  44%|████▍     | 4/9 [00:28<00:35,  7.06s/it]Loading checkpoint shards:  56%|█████▌    | 5/9 [00:35<00:27,  6.82s/it]Loading checkpoint shards:  67%|██████▋   | 6/9 [00:49<00:27,  9.15s/it]Loading checkpoint shards:  78%|███████▊  | 7/9 [00:55<00:16,  8.39s/it]Loading checkpoint shards:  89%|████████▉ | 8/9 [01:02<00:07,  7.75s/it]Loading checkpoint shards: 100%|██████████| 9/9 [01:07<00:00,  7.11s/it]Loading checkpoint shards: 100%|██████████| 9/9 [01:07<00:00,  7.55s/it]
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/generation/utils.py:1261: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
